<a href="https://colab.research.google.com/github/YidaniaLoor/inteligencia/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importe numpy como np y vea la versión

In [1]:
import numpy as np
np. __version__

'1.22.4'

Crear una matriz 1D de números del 0 al 9

In [2]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(array)

[1 2 3 4 5 6 7 8 9]


Cree una matriz numpy de 3 × 3 de todos los True

In [6]:
array = np.ones((3, 3), dtype=bool)
print(array)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


Extrae todos los números impares de la matriz

In [8]:
odd_numbers = array[array % 2 !=0]
print(odd_numbers)

[ True  True  True  True  True  True  True  True  True]


Reemplace todos los números impares en la matriz con -1

In [9]:
array[array % 2 != 0] = -1
print(array)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


Convierta una matriz 1D en una matriz 2D con 2 filas

In [10]:
matriz1d= np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
matriz2d = matriz1d.reshape(2, -1)
print(matriz2d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


Apilar matrices a y b verticalmente

In [11]:
A = np.array([1, 2, 3, 4, 5])
B = np.array([6, 7, 8, 9, 10])

stacked = np.vstack((A, B))
print(stacked)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


Apila las matrices a y b horizontalmente

In [12]:
A = np.array([1, 2, 3, 4, 5])
B = np.array([6, 7, 8, 9, 10])

stacked = np.hstack((A, B))
print(stacked)

[ 1  2  3  4  5  6  7  8  9 10]


Obtenga todos los artículos entre 5 y 10 de a.

In [13]:
a = np.arange(15)
print(a[5:11])

[ 5  6  7  8  9 10]


¿Cómo hacer una función de python que maneje escalares para trabajar en matrices numpy?

In [18]:
def suma_escalar(matriz, escalar):
    resultado = np.add(matriz, escalar)
    return resultado
    a = np.array([5, 7, 9, 8, 6, 4, 5])
    b = np.array([6, 3, 4, 8, 9, 7, 1])

resultado= suma_escalar(a, b)
print(resultado)

NameError: ignored

Intercambiar las columnas 1 y 2 en la matriz

In [19]:
matriz = np.array([[4, 5, 1], [2, 3, 7], [6, 8, 9]])
matriz[:, [1, 2]] = matriz[:, [2, 1]]
print(matriz)

[[4 1 5]
 [2 7 3]
 [6 9 8]]


Cree una matriz 2D de forma 5x3 para contener números decimales aleatorios entre 5 y 10.

In [20]:
matriz = np.random.uniform(5, 10, size=(5, 3))
print(matriz)

[[8.20470795 7.23691894 9.75124255]
 [9.5751132  9.46211879 7.340368  ]
 [6.37264459 6.41778554 9.58782137]
 [5.32509172 6.19011303 9.26647749]
 [5.04541133 5.39125495 5.3098916 ]]
